// ========================================================
// UNIZIK Official Digital Library Catalog & Study Materials
// Curated for official ZikShare institutional account (rc5632250@gmail.com)
// ========================================================

export const UNIZIK_OFFICIAL_STUDY_PACKS = [
  // ── GENERAL STUDIES (GST & CED) ──
  {
    code: 'GST 101',
    title: 'GST 101: Use of English & Communication - Complete 5-Year Past Questions & Essay Marking Scheme',
    faculty: 'General Studies (GST / CED)',
    department: 'GST Directorate',
    level: '100L',
    category: 'Academic & Study Materials',
    subcategory: 'past-questions',
    material_type: 'past-questions',
    priceKobo: 50000, // ₦500
    file_size_bytes: 4200000, // 4.2 MB
    page_count: 84,
    description: 'Comprehensive GST 101 study pack for UNIZIK 100L students. Includes 5 years of verified past questions, grammar rules, concord analysis, phonetics breakdown, and sample essay solutions with official marking criteria.',
    tags: ['GST 101', 'English', 'Past Questions', 'Grammar', '100L', 'Perm Site', 'General Studies'],
    is_official: true,
  },
  {
    code: 'GST 102',
    title: 'GST 102: Philosophy & Logic - Key Summary Points, Fallacies Guide & Solved Questions',
    faculty: 'General Studies (GST / CED)',
    department: 'GST Directorate',
    level: '100L',
    category: 'Academic & Study Materials',
    subcategory: 'lecture-notes',
    material_type: 'lecture-notes',
    priceKobo: 50000, // ₦500
    file_size_bytes: 3600000, // 3.6 MB
    page_count: 62,
    description: 'Concise, high-yield summary of GST 102 Philosophy & Logic. Covers branches of philosophy, logic & arguments, formal/informal fallacies, symbolic logic truth tables, and 200+ solved practice MCQs.',
    tags: ['GST 102', 'Philosophy', 'Logic', 'Truth Tables', 'Summaries', '100L'],
    is_official: true,
  },
  {
    code: 'GST 103',
    title: 'GST 103: Nigerian Peoples & Culture - Exam Revision Handout & Cultural Heritage Guide',
    faculty: 'General Studies (GST / CED)',
    department: 'GST Directorate',
    level: '100L',
    category: 'Academic & Study Materials',
    subcategory: 'lecture-notes',
    material_type: 'lecture-notes',
    priceKobo: 50000, // ₦500
    file_size_bytes: 3100000,
    page_count: 55,
    description: 'Official UNIZIK GST 103 revision handout detailing ethnic origins, pre-colonial institutions, colonial impact, post-independence socio-cultural dynamics, and past exam questions.',
    tags: ['GST 103', 'Culture', 'History', '100L', 'General Studies'],
    is_official: true,
  },
  {
    code: 'GST 110',
    title: 'GST 110: Science, Technology & Society - Comprehensive Study Guide & Past Exam Solutions',
    faculty: 'General Studies (GST / CED)',
    department: 'GST Directorate',
    level: '100L',
    category: 'Academic & Study Materials',
    subcategory: 'past-questions',
    material_type: 'past-questions',
    priceKobo: 60000, // ₦600
    file_size_bytes: 4800000,
    page_count: 76,
    description: 'Essential GST 110 reader for non-science and science majors. Covers evolution of technology, ecological crises, energy systems, biotechnology ethics, and 4-year compiled CBT past questions.',
    tags: ['GST 110', 'Science', 'Technology', '100L', 'CBT Prep'],
    is_official: true,
  },
  {
    code: 'GST 112',
    title: 'GST 112: Peace & Conflict Resolution - Master Summary & 6-Year Solved Questions',
    faculty: 'General Studies (GST / CED)',
    department: 'GST Directorate',
    level: '100L',
    category: 'Academic & Study Materials',
    subcategory: 'past-questions',
    material_type: 'past-questions',
    priceKobo: 50000, // ₦500
    file_size_bytes: 3900000,
    page_count: 68,
    description: 'Comprehensive preparation pack for GST 112 Peace Studies. Explains conflict theories, mediation stages, international conflict mechanisms, security dynamics, and exam answer templates.',
    tags: ['GST 112', 'Peace Studies', 'Conflict Resolution', '100L', 'Past Questions'],
    is_official: true,
  },
  {
    code: 'CED 341',
    title: 'CED 341: Basic Entrepreneurship Studies - Feasibility Plan Master Template & Exam Compendium',
    faculty: 'General Studies (GST / CED)',
    department: 'Centre for Entrepreneurship Development (CED)',
    level: '300L',
    category: 'Academic & Study Materials',
    subcategory: 'lecture-notes',
    material_type: 'lecture-notes',
    priceKobo: 75000, // ₦750
    file_size_bytes: 5600000,
    page_count: 92,
    description: 'Complete CED 341 guide across all UNIZIK 300L departments. Includes 10 real-world Nigerian student feasibility study blueprints, business plan financial models, and past theory questions.',
    tags: ['CED 341', 'Entrepreneurship', 'Business Plan', 'Feasibility Study', '300L'],
    is_official: true,
  },

  // ── FACULTY OF ENGINEERING ──
  {
    code: 'FEG 280',
    title: 'FEG 280: Engineering Mathematics I - Complete Formula Compendium & Step-by-Step Solved Past Exams',
    faculty: 'Faculty of Engineering',
    department: 'Mechanical Engineering',
    level: '200L',
    category: 'Academic & Study Materials',
    subcategory: 'past-questions',
    material_type: 'past-questions',
    priceKobo: 80000, // ₦800
    file_size_bytes: 6500000,
    page_count: 110,
    description: 'Ultimate 200L engineering maths survival guide. Covers Differential & Integral Calculus, Matrices & Determinants, Vector Analysis, Complex Numbers, and detailed step-by-step solutions to 2018–2024 UNIZIK exams.',
    tags: ['FEG 280', 'Engineering Maths', 'Calculus', 'Vectors', '200L', 'Engineering'],
    is_official: true,
  },
  {
    code: 'FEG 281',
    title: 'FEG 281: Applied Mechanics (Statics) - Free-Body Diagram Mastery & Problem Solutions',
    faculty: 'Faculty of Engineering',
    department: 'Civil Engineering',
    level: '200L',
    category: 'Academic & Study Materials',
    subcategory: 'past-questions',
    material_type: 'past-questions',
    priceKobo: 75000, // ₦750
    file_size_bytes: 5800000,
    page_count: 96,
    description: 'Comprehensive applied mechanics pack for UNIZIK engineering students. Includes truss analysis (method of joints and sections), friction, centroids, moments of inertia, and 50+ worked exam problems.',
    tags: ['FEG 281', 'Mechanics', 'Statics', 'Trusses', 'Civil Engineering', '200L'],
    is_official: true,
  },
  {
    code: 'FEG 282',
    title: 'FEG 282: Engineering Thermodynamics - First & Second Law Worksheets with Steam Tables',
    faculty: 'Faculty of Engineering',
    department: 'Mechanical Engineering',
    level: '200L',
    category: 'Academic & Study Materials',
    subcategory: 'lecture-notes',
    material_type: 'lecture-notes',
    priceKobo: 80000, // ₦800
    file_size_bytes: 6200000,
    page_count: 104,
    description: 'Core 200L Thermodynamics lecture notes and tutorial solutions. Covers closed and open systems, Otto/Diesel/Carnot cycles, entropy calculations, and steam property interpolation formulas.',
    tags: ['FEG 282', 'Thermodynamics', 'Carnot', 'Steam Tables', '200L'],
    is_official: true,
  },
  {
    code: 'EEE 311',
    title: 'EEE 311: Circuit Theory & Network Analysis - Mesh, Nodal & Laplace Transform Solved Problems',
    faculty: 'Faculty of Engineering',
    department: 'Electrical Engineering',
    level: '300L',
    category: 'Academic & Study Materials',
    subcategory: 'past-questions',
    material_type: 'past-questions',
    priceKobo: 90000, // ₦900
    file_size_bytes: 7100000,
    page_count: 120,
    description: 'In-depth Circuit Theory problem solver. Contains Thevenin/Norton conversions, 2-port network parameters, RLC resonant circuits, Fourier/Laplace transients, and past UNIZIK examination papers.',
    tags: ['EEE 311', 'Circuit Theory', 'Laplace', 'Electrical Engineering', '300L'],
    is_official: true,
  },

  // ── FACULTY OF PHYSICAL SCIENCES ──
  {
    code: 'MTH 101',
    title: 'MTH 101: Elementary Mathematics I (Algebra & Trigonometry) - Complete Solved Past Questions',
    faculty: 'Faculty of Physical Sciences',
    department: 'Mathematics',
    level: '100L',
    category: 'Academic & Study Materials',
    subcategory: 'past-questions',
    material_type: 'past-questions',
    priceKobo: 60000, // ₦600
    file_size_bytes: 5200000,
    page_count: 98,
    description: 'High-rated MTH 101 examination manual. Covers Set Theory, Real Number System, Quadratic Equations, Binomial Theorem, Mathematical Induction, Complex Numbers, and Trigonometric Identities with full workings.',
    tags: ['MTH 101', 'Algebra', 'Trigonometry', '100L', 'Physical Sciences'],
    is_official: true,
  },
  {
    code: 'PHY 101',
    title: 'PHY 101: General Physics I (Mechanics, Properties of Matter & Waves) - Solved Compendium',
    faculty: 'Faculty of Physical Sciences',
    department: 'Physics & Industrial Physics',
    level: '100L',
    category: 'Academic & Study Materials',
    subcategory: 'past-questions',
    material_type: 'past-questions',
    priceKobo: 60000, // ₦600
    file_size_bytes: 5400000,
    page_count: 90,
    description: 'Full solutions to UNIZIK PHY 101 past questions. Features dimensional analysis, projectile motion, circular dynamics, simple harmonic motion, fluid mechanics, wave equations, and key formula summary cards.',
    tags: ['PHY 101', 'Physics', 'Mechanics', 'Waves', '100L'],
    is_official: true,
  },
  {
    code: 'CHM 101',
    title: 'CHM 101: General Chemistry I (Inorganic & Physical Chemistry) - Concise Handout & Question Bank',
    faculty: 'Faculty of Physical Sciences',
    department: 'Chemistry',
    level: '100L',
    category: 'Academic & Study Materials',
    subcategory: 'lecture-notes',
    material_type: 'lecture-notes',
    priceKobo: 60000, // ₦600
    file_size_bytes: 4900000,
    page_count: 82,
    description: 'Clear, well-diagrammed CHM 101 revision text. Covers Atomic Structure, Periodic Table trends, Chemical Bonding, Chemical Kinetics, Gas Laws, and Equilibrium calculations.',
    tags: ['CHM 101', 'Chemistry', 'Kinetics', 'Equilibrium', '100L'],
    is_official: true,
  },
  {
    code: 'CSC 101',
    title: 'CSC 101: Introduction to Computer Science & Problem Solving - Handout & Practice Tests',
    faculty: 'Faculty of Physical Sciences',
    department: 'Computer Science',
    level: '100L',
    category: 'Academic & Study Materials',
    subcategory: 'lecture-notes',
    material_type: 'lecture-notes',
    priceKobo: 50000, // ₦500
    file_size_bytes: 4100000,
    page_count: 70,
    description: 'Beginner-friendly Computer Science pack. Features Computer Architecture fundamentals, binary arithmetic, flowcharts, pseudocode problem solving, operating systems, and internet fundamentals.',
    tags: ['CSC 101', 'Computer Science', 'Algorithms', 'Flowcharts', '100L'],
    is_official: true,
  },
  {
    code: 'CSC 201',
    title: 'CSC 201: Object-Oriented Programming (C++ & Java) - Comprehensive Code Manual & Past Labs',
    faculty: 'Faculty of Physical Sciences',
    department: 'Computer Science',
    level: '200L',
    category: 'Academic & Study Materials',
    subcategory: 'lab-manuals',
    material_type: 'lab-manuals',
    priceKobo: 75000, // ₦750
    file_size_bytes: 6800000,
    page_count: 114,
    description: 'Practical programming manual for UNIZIK CSC 201. Covers classes, objects, inheritance, polymorphism, encapsulation, file I/O, exception handling, and 30+ runnable lab projects.',
    tags: ['CSC 201', 'OOP', 'C++', 'Java', 'Programming', '200L'],
    is_official: true,
  },

  // ── FACULTY OF MANAGEMENT SCIENCES ──
  {
    code: 'ACC 101',
    title: 'ACC 101: Principles of Accounting I - Complete Double Entry, Ledgers & Final Accounts Masterclass',
    faculty: 'Faculty of Management Sciences',
    department: 'Accountancy',
    level: '100L',
    category: 'Academic & Study Materials',
    subcategory: 'lecture-notes',
    material_type: 'lecture-notes',
    priceKobo: 70000, // ₦700
    file_size_bytes: 5500000,
    page_count: 102,
    description: 'Detailed accounting study pack for UNIZIK management students. Covers Double-Entry Bookkeeping, Books of Prime Entry, Trial Balance adjustments, Bad Debts, Depreciation methods, and Trading Profit & Loss Balance Sheets.',
    tags: ['ACC 101', 'Accounting', 'Double Entry', 'Balance Sheet', '100L', 'Management'],
    is_official: true,
  },
  {
    code: 'ECO 101',
    title: 'ECO 101: Principles of Economics I (Microeconomics) - Demand/Supply Diagrams & Past Questions',
    faculty: 'Faculty of Management Sciences',
    department: 'Banking & Finance',
    level: '100L',
    category: 'Academic & Study Materials',
    subcategory: 'past-questions',
    material_type: 'past-questions',
    priceKobo: 60000, // ₦600
    file_size_bytes: 4600000,
    page_count: 86,
    description: 'Thorough Microeconomics revision pack. Features Price Theory, Elasticity of Demand & Supply, Consumer Behavior (Utility & Indifference Curves), Production Costs, and Market Structures.',
    tags: ['ECO 101', 'Economics', 'Microeconomics', 'Elasticity', '100L'],
    is_official: true,
  },
  {
    code: 'BUS 101',
    title: 'BUS 101: Introduction to Business Administration - Key Concept Summaries & Exam Answers',
    faculty: 'Faculty of Management Sciences',
    department: 'Business Administration',
    level: '100L',
    category: 'Academic & Study Materials',
    subcategory: 'lecture-notes',
    material_type: 'lecture-notes',
    priceKobo: 50000, // ₦500
    file_size_bytes: 3800000,
    page_count: 64,
    description: 'Concise business management companion. Explains forms of business ownership in Nigeria, organizational structures, management functions (planning, organizing, leading, controlling), and ethics.',
    tags: ['BUS 101', 'Business Admin', 'Management', '100L'],
    is_official: true,
  },

  // ── FACULTY OF LAW ──
  {
    code: 'LAW 101',
    title: 'LAW 101: Legal Method & Nigerian Legal System - Core Landmark Cases & Essay Structure Guide',
    faculty: 'Faculty of Law',
    department: 'Public & Private Law',
    level: '100L',
    category: 'Academic & Study Materials',
    subcategory: 'lecture-notes',
    material_type: 'lecture-notes',
    priceKobo: 85000, // ₦850
    file_size_bytes: 6700000,
    page_count: 118,
    description: 'Indispensable study manual for UNIZIK Law freshmen. Covers sources of Nigerian Law, statutory interpretation rules, hierarchy of courts, doctrine of judicial precedent (Stare Decisis), and IRAC essay methodology.',
    tags: ['LAW 101', 'Legal Method', 'Case Law', 'Stare Decisis', '100L', 'Law Complex'],
    is_official: true,
  },
  {
    code: 'LAW 201',
    title: 'LAW 201: Nigerian Constitutional Law - Fundamental Rights, Separation of Powers & Supreme Court Rulings',
    faculty: 'Faculty of Law',
    department: 'Public & Private Law',
    level: '200L',
    category: 'Academic & Study Materials',
    subcategory: 'textbooks',
    material_type: 'textbooks',
    priceKobo: 95000, // ₦950
    file_size_bytes: 7800000,
    page_count: 140,
    description: 'Comprehensive Constitutional Law compendium based on the 1999 Constitution as amended. Covers executive immunity, judicial review, fundamental human rights enforcement, and landmark locus standi cases.',
    tags: ['LAW 201', 'Constitutional Law', '1999 Constitution', 'Human Rights', '200L'],
    is_official: true,
  },

  // ── FACULTY OF BIOSCIENCES ──
  {
    code: 'BIO 101',
    title: 'BIO 101: General Biology I (Cell Biology, Histology & Genetics) - Illustrated Lecture Notes',
    faculty: 'Faculty of Biosciences',
    department: 'Microbiology',
    level: '100L',
    category: 'Academic & Study Materials',
    subcategory: 'lecture-notes',
    material_type: 'lecture-notes',
    priceKobo: 60000, // ₦600
    file_size_bytes: 5200000,
    page_count: 94,
    description: 'Illustrated BIO 101 guide for biological, medical, and agricultural students. Covers Prokaryotic vs Eukaryotic cells, Mitosis/Meiosis, Mendelian genetics, plant/animal tissues, and sample exam questions.',
    tags: ['BIO 101', 'Biology', 'Cell Biology', 'Genetics', '100L'],
    is_official: true,
  },
  {
    code: 'BCH 201',
    title: 'BCH 201: General Biochemistry I - Biomolecules, Enzyme Kinetics & Metabolic Cycles Guide',
    faculty: 'Faculty of Biosciences',
    department: 'Applied Biochemistry',
    level: '200L',
    category: 'Academic & Study Materials',
    subcategory: 'lecture-notes',
    material_type: 'lecture-notes',
    priceKobo: 80000, // ₦800
    file_size_bytes: 6100000,
    page_count: 108,
    description: 'Detailed biochemistry handbook. Features carbohydrate/lipid structures, amino acid peptide bonds, Michaelis-Menten enzyme kinetics, Lineweaver-Burk plots, glycolysis, and TCA cycle diagrams.',
    tags: ['BCH 201', 'Biochemistry', 'Enzymes', 'Glycolysis', '200L', 'Science Village'],
    is_official: true,
  },

  // ── FACULTY OF SOCIAL SCIENCES ──
  {
    code: 'SOC 101',
    title: 'SOC 101: Introduction to Sociology - Classical Thinkers, Social Institutions & Practice Questions',
    faculty: 'Faculty of Social Sciences',
    department: 'Sociology/Anthropology',
    level: '100L',
    category: 'Academic & Study Materials',
    subcategory: 'lecture-notes',
    material_type: 'lecture-notes',
    priceKobo: 50000, // ₦500
    file_size_bytes: 3900000,
    page_count: 72,
    description: 'Introductory Sociology study pack. Covers Karl Marx, Emile Durkheim, Max Weber, social stratification, family/religion institutions, deviance, and UNIZIK exam past papers.',
    tags: ['SOC 101', 'Sociology', 'Durkheim', 'Social Sciences', '100L'],
    is_official: true,
  },
  {
    code: 'POL 101',
    title: 'POL 101: Introduction to Political Science - Theories of State, Power & Political Ideologies',
    faculty: 'Faculty of Social Sciences',
    department: 'Political Science',
    level: '100L',
    category: 'Academic & Study Materials',
    subcategory: 'past-questions',
    material_type: 'past-questions',
    priceKobo: 55000, // ₦550
    file_size_bytes: 4300000,
    page_count: 78,
    description: 'Comprehensive Political Science foundation manual. Explains sovereignty, forms of government (presidential vs parliamentary), political parties, electoral systems, and 4-year exam questions.',
    tags: ['POL 101', 'Political Science', 'Sovereignty', 'Democracy', '100L'],
    is_official: true,
  },
]
